import fs from 'fs';
import path from 'path';
import type { InstallContext, InstallResult, ToolInstaller, UninstallContext } from '../types';

const EXTENSION_STUB = `// Copydoc extension for Pi
// Auto-generated by @copydoc/integrations
//
// This extension wraps @copydoc/core to provide copywriting
// capabilities within Pi. Install @copydoc/core as a dependency
// to use this extension.

import { createLoader, createAssembler, selectFramework, createAntiSlopChecker } from '@copydoc/core';
import path from 'path';

const skillsDir = path.resolve(__dirname, '../skills/copydoc');

export function createCopydocExtension() {
  const loader = createLoader(skillsDir);
  const assembler = createAssembler(loader, selectFramework);
  const checker = createAntiSlopChecker(loader);
  return { loader, assembler, checker };
}
`;

function piDir(projectDir: string): string {
  return path.join(projectDir, '.pi');
}

function skillsLinkPath(projectDir: string): string {
  return path.join(piDir(projectDir), 'skills', 'copydoc');
}

function extensionStubPath(projectDir: string): string {
  return path.join(piDir(projectDir), 'extensions', 'copydoc.ts');
}

function copyDirRecursive(src: string, dest: string): void {
  fs.mkdirSync(dest, { recursive: true });
  const entries = fs.readdirSync(src, { withFileTypes: true });
  for (const entry of entries) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      copyDirRecursive(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

export const piInstaller: ToolInstaller = {
  name: 'pi',

  async install(ctx: InstallContext): Promise<InstallResult> {
    const actions: string[] = [];

    // Step 1: create skills symlink (or copy)
    const skillsParentDir = path.join(piDir(ctx.projectDir), 'skills');
    if (!fs.existsSync(skillsParentDir)) {
      fs.mkdirSync(skillsParentDir, { recursive: true });
    }

    const linkPath = skillsLinkPath(ctx.projectDir);
    const linkExists = (() => {
      try {
        fs.lstatSync(linkPath);
        return true;
      } catch {
        return false;
      }
    })();

    if (linkExists) {
      actions.push('.pi/skills/copydoc already exists (no change)');
    } else if (ctx.copy) {
      copyDirRecursive(ctx.skillsDir, linkPath);
      actions.push('copied skills directory to .pi/skills/copydoc');
    } else {
      const linkDir = path.dirname(linkPath);
      const relTarget = path.relative(linkDir, ctx.skillsDir);
      fs.symlinkSync(relTarget, linkPath);
      actions.push(`created symlink .pi/skills/copydoc -> ${relTarget}`);
    }

    // Step 2: write TypeScript extension stub
    const extensionsDir = path.join(piDir(ctx.projectDir), 'extensions');
    if (!fs.existsSync(extensionsDir)) {
      fs.mkdirSync(extensionsDir, { recursive: true });
    }

    const stubPath = extensionStubPath(ctx.projectDir);
    fs.writeFileSync(stubPath, EXTENSION_STUB);
    actions.push('generated .pi/extensions/copydoc.ts');

    return { tool: 'pi', actions };
  },

  async uninstall(ctx: UninstallContext): Promise<void> {
    // Remove extension stub
    const stubPath = extensionStubPath(ctx.projectDir);
    try {
      fs.unlinkSync(stubPath);
    } catch {
      // Does not exist, nothing to do
    }

    // Remove symlink or copied directory
    const linkPath = skillsLinkPath(ctx.projectDir);
    try {
      const stat = fs.lstatSync(linkPath);
      if (stat.isSymbolicLink()) {
        fs.unlinkSync(linkPath);
      } else if (stat.isDirectory()) {
        fs.rmSync(linkPath, { recursive: true, force: true });
      }
    } catch {
      // Does not exist, nothing to do
    }

    // Remove empty parent directories
    const extensionsDir = path.join(piDir(ctx.projectDir), 'extensions');
    try {
      if (fs.existsSync(extensionsDir) && fs.readdirSync(extensionsDir).length === 0) {
        fs.rmdirSync(extensionsDir);
      }
    } catch {
      // Ignore errors removing empty dirs
    }

    const skillsParentDir = path.join(piDir(ctx.projectDir), 'skills');
    try {
      if (fs.existsSync(skillsParentDir) && fs.readdirSync(skillsParentDir).length === 0) {
        fs.rmdirSync(skillsParentDir);
      }
    } catch {
      // Ignore errors removing empty dirs
    }
  },

  async isConfigured(projectDir: string): Promise<boolean> {
    return fs.existsSync(extensionStubPath(projectDir));
  },
};
